// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHphTdD-oh_k50s8wtN_aALX5fhqKf4c',
    appId: '1:876521885587:web:4f1a650af4d6e28f916266',
    messagingSenderId: '876521885587',
    projectId: 'avisror-prod',
    authDomain: 'avisror-prod.firebaseapp.com',
    storageBucket: 'avisror-prod.firebasestorage.app',
    measurementId: 'G-4YRGV0CEPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzuZZE2m7HLm3yuyqL0IRcJ6dRyU3k20E',
    appId: '1:876521885587:android:401fcb4c63975c1e916266',
    messagingSenderId: '876521885587',
    projectId: 'avisror-prod',
    storageBucket: 'avisror-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKRfOv7QnWJ1sxAukrMGKM4tnegpBjx0',
    appId: '1:876521885587:ios:a4e45545c5261f55916266',
    messagingSenderId: '876521885587',
    projectId: 'avisror-prod',
    storageBucket: 'avisror-prod.firebasestorage.app',
    iosBundleId: 'com.avisror.app',
  );
}
