// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqsKJiXg5oJhmQ8EjRjZEbTMou1lqsi-k',
    appId: '1:515323707514:web:4743e29b567230bd143bc3',
    messagingSenderId: '515323707514',
    projectId: 'avisror-dev',
    authDomain: 'avisror-dev.firebaseapp.com',
    storageBucket: 'avisror-dev.firebasestorage.app',
    measurementId: 'G-HZRK6BS0T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuM2BYosm1ea89q73S5yfihS4mnmkrfm4',
    appId: '1:515323707514:android:a2c74fa1c3f99ebc143bc3',
    messagingSenderId: '515323707514',
    projectId: 'avisror-dev',
    storageBucket: 'avisror-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxB0331M3GYWn4cwROtqoq553vfbK7kZw',
    appId: '1:515323707514:ios:6e72f57a5a728a01143bc3',
    messagingSenderId: '515323707514',
    projectId: 'avisror-dev',
    storageBucket: 'avisror-dev.firebasestorage.app',
    iosBundleId: 'com.avisror.app.dev',
  );

}